version: '3.3'

services:
  grafana:
    image: grafana/grafana:8.0.3
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
    volumes:
      - grafana-data:/var/lib/grafana
      - ../shared_docker/grafana/:/etc/grafana/provisioning/
    env_file:
      - ../shared_docker/grafana/.env

volumes:
  grafana-data: {}
