{
 "title": "PromEx - BEAM Dashboard",
 "description": "All the data that is presented here is captured by the PromEx BEAM plugin (https://github.com/akoutmos/prom_ex/blob/master/lib/prom_ex/plugins/beam.ex)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "BEAM Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Stats on the current memory usage.",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    { "expr": "beam_memory_total_kilobytes", "legendFormat": "Total Usage" },
    {
     "expr": "beam_memory_atom_total_kilobytes",
     "legendFormat": "Atoms"
    },
    {
     "expr": "beam_memory_binary_total_kilobytes",
     "legendFormat": "Binaries"
    },
    {
     "expr": "beam_memory_code_total_kilobytes",
     "legendFormat": "Code"
    },
    {
     "expr": "beam_memory_ets_total_kilobytes",
     "legendFormat": "ETS"
    }
   ]
  },
  {
   "title": "Active Ports",
   "type": "graph",
   "description": "The number of active ports.",
   "gridPos": { "h": 15, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Ports" }
   ],
   "targets": [
    { "expr": "beam_stats_port_count", "legendFormat": "Active Ports" }
   ]
  },
  {
   "title": "Active BEAM Processes",
   "type": "graph",
   "description": "The number of running BEAM processes.",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Processes" }
   ],
   "targets": [
    { "expr": "beam_stats_process_count", "legendFormat": "Active Processes" }
   ]
  },
  {
   "title": "Atom Table Size",
   "type": "graph",
   "description": "The number of atoms currently in the atom table",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "yaxes": [
    { "format": "locale", "label": "Atoms" }
   ],
   "targets": [
    { "expr": "beam_stats_atom_count", "legendFormat": "Active ports" }
   ]
  },
  {
   "title": "ETS",
   "type": "graph",
   "description": "The number of active ETS tables.",
   "gridPos": { "h": 15, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Tables" }
   ],
   "targets": [
    { "expr": "beam_stats_ets_count", "legendFormat": "Active ETS Tables" }
   ]
  },
  { "title": "System Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "OTP Major Version",
   "type": "stat",
   "description": "The OTP major version running the application.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "beam_system_version_info" }
   ]
  },
  {
   "title": "Word Size in Bytes",
   "type": "stat",
   "description": "The size of Erlang term words in bytes.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beam_system_word_size_bytes_info"
    }
   ]
  },
  {
   "title": "Logical Processors",
   "type": "stat",
   "description": "The number of logical processors in the system.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beam_system_logical_processors_info"
    }
   ]
  },
  {
   "title": "Logical Processors Available",
   "type": "stat",
   "description": "The number of logical processors available in the system.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beam_system_logical_processors_available_info"
    }
   ]
  },
  {
   "title": "Logical Processors Online",
   "type": "stat",
   "description": "The number of logical processors online in the system.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beam_system_logical_processors_online_info"
    }
   ]
  },
  {
   "title": "OTP Compiler Options",
   "type": "table",
   "description": "Shows the various options that OTP was compiled with.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "{__name__=~\"beam_system_thread_support_info|beam_system_smp_support_info|beam_system_time_correction_support_info\"}"
    }
   ]
  },
  {
   "title": "System Limits",
   "type": "table",
   "description": "Shows information regarding the system limits of the BEAM instance.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "targets": [
    {
     "expr": "{__name__=~\"beam_system_ets_limit_info|beam_system_port_limit_info|beam_system_process_limit_info|beam_system_atom_limit_info\"}"
    }
   ]
  },
  {
   "title": "Scheduler Information",
   "type": "table",
   "description": "Shows information regarding the schedulers configured for the BEAM instance.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "targets": [
    {
     "expr": "{__name__=~\"beam_system_dirty_cpu_schedulers_info|beam_system_dirty_cpu_schedulers_online_info|beam_system_dirty_io_schedulers_info|beam_system_schedulers_info|beam_system_schedulers_online_info\"}"
    }
   ]
  }
 ]
}