{
 "title": "PromEx - Phoenix Dashboard Copy",
 "description": "All the data that is presented here is captured by the PromEx Phoenix plugin (https://github.com/akoutmos/prom_ex/blob/master/lib/prom_ex/plugins/phoenix.ex)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "HTTP Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Time",
   "type": "heatmap",
   "description": "A heatmap showing the request time spread across all requests (regardless of path).",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(irate(phoenix_http_request_duration_milliseconds_bucket[30s])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Response Payload Size",
   "type": "heatmap",
   "description": "A heatmap showing the response payload size spread across all requests (regardless of path).",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(irate(phoenix_http_response_size_bytes_bucket[30s])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Average HTTP Request Time",
   "type": "graph",
   "description": "The average request time per path per status code per HTTP method.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms", "label": "Requests" }
   ],
   "targets": [
    {
     "expr": "sum(irate(phoenix_http_request_duration_milliseconds_sum[30s])) by(path) / sum(irate(phoenix_http_request_duration_milliseconds_count[30s])) by(path)",
     "legendFormat": "{{ method }} {{ path }} :: {{ status }}"
    }
   ]
  },
  {
   "title": "Average HTTP Response Size",
   "type": "graph",
   "description": "The average response size per path per status code per HTTP method.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "decbytes", "label": "Requests" }
   ],
   "targets": [
    {
     "expr": "sum(irate(phoenix_http_response_size_bytes_sum[30s])) by(path) / sum(irate(phoenix_http_response_size_bytes_count[30s])) by(path)",
     "legendFormat": "{{ method }} {{ path }} :: {{ status }}"
    }
   ]
  },
  {
   "title": "Path Requests",
   "type": "graph",
   "description": "Shows the number of requests coming into certain paths and the resulting response codes.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "locale", "label": "Requests" }
   ],
   "targets": [
    {
     "expr": "irate(phoenix_http_requests_total[30s])",
     "legendFormat": "{{ method }} {{ path }} :: {{ status }}"
    }
   ]
  },
  {
   "title": "Response Status Codes",
   "type": "graph",
   "description": "The aggregate response status of all the requests.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "Requests" }
   ],
   "targets": [
    {
     "expr": "sum(irate(phoenix_http_requests_total{status=~\"2..\"}[30s]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(irate(phoenix_http_requests_total{status=~\"4..\"}[30s]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(irate(phoenix_http_requests_total{status=~\"5..\"}[30s]))",
     "legendFormat": "5xx"
    }
   ]
  },
  { "title": "Channel Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } }
 ]
}