version: '3.3'

services:
  elixir_app_one:
    image: elixir:1.10.4
    command: >
      /bin/sh -c 'apt-get update && apt-get install -y inotify-tools &&
      cd /app &&
      mix local.hex --force &&
      mix local.rebar --force &&
      mix deps.get &&
      mix ecto.setup &&
      mix prom_ex.dashboard.publish &&
      exec elixir --sname elixir_app_one --cookie super_secret -S mix phx.server'
    ports:
      - '4000:4000'
      - '4021:4021'
      - '4022:4022'
    depends_on:
      - postgres
      - grafana
    working_dir: /app
    environment:
      POSTGRES_HOST: 'postgres'
      GIT_SHA: '0fa5476'
      GIT_AUTHOR: 'Alex Koutmos'
      GRAFANA_TOKEN: 'eyJrIjoiZktmWTdDSkpjMTJWbmkwTG1qTDAxZHdUQzNKZXB1ZDAiLCJuIjoiUHJvbUV4IiwiaWQiOjF9'
      GRAFANA_DATASOURCE: 'prometheus'
    volumes:
      - ./config:/app/config:ro
      - ./lib:/app/lib:ro
      - ./priv:/app/priv:ro
      - ./.formatter.exs:/app/formatter.exs:ro
      - ./mix.exs:/app/mix.exs:ro
      - ./mix.lock:/app/mix.lock:ro
      - elixir-deps-one:/app/deps/
      - elixir-build-one:/app/_build/

  elixir_app_two:
    image: elixir:1.10.4
    command: >
      /bin/sh -c 'apt-get update && apt-get install -y inotify-tools &&
      cd /app &&
      mix local.hex --force &&
      mix local.rebar --force &&
      mix deps.get &&
      mix ecto.setup &&
      mix prom_ex.dashboard.publish &&
      exec elixir --sname elixir_app_two --cookie super_secret -S mix phx.server'
    ports:
      - '4100:4000'
      - '4121:4021'
      - '4122:4022'
    depends_on:
      - postgres
      - grafana
    working_dir: /app
    environment:
      POSTGRES_HOST: 'postgres'
      GIT_SHA: '0fa5476'
      GIT_AUTHOR: 'Alex Koutmos'
      GRAFANA_TOKEN: 'eyJrIjoiZktmWTdDSkpjMTJWbmkwTG1qTDAxZHdUQzNKZXB1ZDAiLCJuIjoiUHJvbUV4IiwiaWQiOjF9'
      GRAFANA_DATASOURCE: 'prometheus'
    volumes:
      - ./config:/app/config:ro
      - ./lib:/app/lib:ro
      - ./priv:/app/priv:ro
      - ./.formatter.exs:/app/formatter.exs:ro
      - ./mix.exs:/app/mix.exs:ro
      - ./mix.lock:/app/mix.lock:ro
      - elixir-deps-two:/app/deps/
      - elixir-build-two:/app/_build/

volumes:
  elixir-deps-one: {}
  elixir-build-one: {}
  elixir-deps-two: {}
  elixir-build-two: {}
